// This file was generated by scripts/generate-zod-combinedTypes.js at Thu, 16 May 2024 01:44:09 GMT

import { z } from "zod";

import { license } from "./license.js";
import { source } from "./source.js";
import { sourceGroup } from "./sourceGroup.js";

const metaType = z.discriminatedUnion("type", [license, source, sourceGroup]);

import { content } from "./_content.js";
export const data = content.or(metaType);
