// This file was generated by scripts/generate-zod-combinedTypes.js at Sun, 11 Feb 2024 03:24:02 GMT
import { z } from "zod";
import { license } from "./license.js";
import { source } from "./source.js";
import { sourceGroup } from "./sourceGroup.js";
import { background } from "./content/background.js";
import { condition } from "./content/condition.js";
import { divineIntercession } from "./content/divineIntercession.js";
import { domain } from "./content/domain.js";
import { event } from "./content/event.js";
import { familiarAbility } from "./content/familiarAbility.js";
import { relicGift } from "./content/relicGift.js";
import { skill } from "./content/skill.js";
export const data = z.discriminatedUnion("type", [
    license,
    source,
    sourceGroup,
    background,
    condition,
    divineIntercession,
    domain,
    event,
    familiarAbility,
    relicGift,
    skill,
]);
